# -*- coding: utf-8 -*-
"""simple_parser.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u0yfxB_rS2Rb9Y1HboQq9z_tAvSLKFkc
"""

pip install pypdf2

import PyPDF2
pdf_Obj = open('/content/Resume22.PDF', 'rb')

# creating a pdf reader object
pdfReader = PyPDF2.PdfFileReader(pdf_Obj)
print(pdfReader.numPages)

page = pdfReader.getPage(0)
print(page.extractText())

#assingn to txt variable
text=page.extractText()

import re

EMAIL_REG = re.compile(r'[a-z0-9\.\-+_]+@[a-z0-9\.\-+_]+\.[a-z]+')

re.findall(EMAIL_REG, text)

ph = re.compile(r"\d\d\d\d\d\d\d\d\d\d\d\d")

a=re.findall(ph,text)
if len(a)==0:
  ph = re.compile(r"\d\d\d\d\d\d\d\d\d\d")
  a=re.findall(ph,text)
print(a)

pip install nltk

import nltk
 nltk.download('punkt')

from nltk import word_tokenize
tk=word_tokenize(text)



